version: '3'

services:
  app:
    build: .
    container_name: app
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - '3001:3001'
    environment:
      - HOST=0.0.0.0
      - PORT=3001
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
